name: deploy-test-android-app
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: echo $DEBUG_KEYSTORE_FILE | base64 -d > android/debug.keystore
        env:
          DEBUG_KEYSTORE_FILE: ${{ secrets.DEBUG_KEYSTORE_FILE }}
      - run: flutter build apk --debug
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: 'android'
          file: 'build/app/outputs/flutter-apk/app-debug.apk'
